version: '2'
services:
  api:
    build: .
    volumes:
     - /models/:/models/
    restart: always
    ports:
     - 8080
    environment:
     - SERVICE_PORTS=8080
  lb:
    image: 'dockercloud/haproxy:1.2.1'
    links:
     - api
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - BALANCE=leastconn
