version: '2'
services:
  mysql:
    image: mysql
    container_name: mysql-test
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: "mypassword"
      MYSQL_USER: "shane"
      MYSQL_PASSWORD: "S13240sx91"
      MYSQL_DATABASE: "dynamic"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - mysql_net
  api:
    depends_on:
      - mysql
    build: .
    links:
      - mysql:mysql
    volumes:
     - /models/:/models/
    restart: always
    ports:
     - 8080
    environment:
     - SERVICE_PORTS=8080
    networks:
     - mysql_net
  lb:
    image: 'dockercloud/haproxy:1.2.1'
    links:
     - api
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - BALANCE=leastconn
    networks:
     - mysql_net
